### ISSUE TITLE
Error: An error has occured

### ISSUE THREAD

**Issue by indybuell** [smichard/graphR#2]
Running reports against large or small RVtools outputs, all I am receiving is "Error: An error has occured".  Restarting the container and trying to run the report again sometimes works.  Not sure what might be the cause as the report is generated using the same file that previously erred.

**Comment by smichard** [comment]
thanks for reporting the issue.
I am happy to have a lock.
Would it be possible to share with me an anonymized version of the input file?

**Comment by indybuell** [comment]
[RVTools_export_all_2017-08-28_16.15.36-DR SCADA anon.XLSX](https://github.com/smichard/graphR/files/1637027/RVTools_export_all_2017-08-28_16.15.36-DR.SCADA.anon.XLSX)

**Comment by smichard** [comment]
got it.
Thanks, going to do some testing and get back to you

**Comment by smichard** [comment]
please check the columns.
The file you provided is missing the column "Network #1"
Please review and if the issue persists reach out to me again.
