### ISSUE TITLE
Issue with rename

### ISSUE THREAD

**Issue by evgenii-spec** [smichard/graphR#4]
After uploading file it gives me error.
Checked docker logs:
Have this type of error. 
Warning in file.rename(file1$datapath, paste(file1$datapath, ext, sep = ".")) :
  cannot rename file '/tmp/RtmpXZXObW/e5dda85553f2f354ef3403ad/0' to '/tmp/RtmpXZXObW/e5dda85553f2f354ef3403ad/0.xlsx', reason 'No such file or directory'
Warning: Error in [.data.frame: undefined columns selected
Stack trace (innermost first):
    104: [.data.frame
    103: [
    102: eval
    101: eval
    100: withProgress
     99: renderPlot
     89: <reactive:plotObj>
     78: plotObj
     77: origRenderFunc
     76: output$progress_bar_rv
      1: runApp

Check docker folder - file 0.xlsx exist already
The same file works good on launch.graphr.de

**Comment by smichard** [comment]
Thank you for reporting this issue. I've updated the source code to the latest version, which should resolve the error you're experiencing with shiny.js. Please pull the latest changes and try running the application again.

Let me know if you continue to encounter any problems, and I'll be happy to assist further.
